// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_Teretana.Models;

namespace e_Teretana.Migrations
{
    [DbContext(typeof(TeretanaContext))]
    [Migration("20200522104556_Inicijalna")]
    partial class Inicijalna
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_Teretana.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");
                });

            modelBuilder.Entity("e_Teretana.Models.Novost", b =>
                {
                    b.Property<int>("NovostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemeDodavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("NovostID");

                    b.ToTable("Novost");
                });

            modelBuilder.Entity("e_Teretana.Models.Oprema", b =>
                {
                    b.Property<int>("OpremaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikOpremeKorisnikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KrajnjiDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NaCekanju")
                        .HasColumnType("bit");

                    b.Property<string>("NazivOpreme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetniDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sifra")
                        .HasColumnType("int");

                    b.Property<int>("TipZauzetosti")
                        .HasColumnType("int");

                    b.HasKey("OpremaID");

                    b.HasIndex("KorisnikOpremeKorisnikID");

                    b.ToTable("Oprema");
                });

            modelBuilder.Entity("e_Teretana.Models.Trening", b =>
                {
                    b.Property<int>("TreningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("TrenerKorisnikID")
                        .HasColumnType("int");

                    b.HasKey("TreningID");

                    b.HasIndex("TrenerKorisnikID");

                    b.ToTable("Trening");
                });

            modelBuilder.Entity("e_Teretana.Models.Clan", b =>
                {
                    b.HasBaseType("e_Teretana.Models.Korisnik");

                    b.Property<int>("BrojPosjeta")
                        .HasColumnType("int");

                    b.Property<int>("Clanarina")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumUclanjivanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TreningID")
                        .HasColumnType("int");

                    b.Property<bool>("TrenutnoPrisutan")
                        .HasColumnType("bit");

                    b.HasIndex("TreningID");

                    b.HasDiscriminator().HasValue("Clan");
                });

            modelBuilder.Entity("e_Teretana.Models.Trener", b =>
                {
                    b.HasBaseType("e_Teretana.Models.Korisnik");

                    b.HasDiscriminator().HasValue("Trener");
                });

            modelBuilder.Entity("e_Teretana.Models.Oprema", b =>
                {
                    b.HasOne("e_Teretana.Models.Clan", "KorisnikOpreme")
                        .WithMany()
                        .HasForeignKey("KorisnikOpremeKorisnikID");
                });

            modelBuilder.Entity("e_Teretana.Models.Trening", b =>
                {
                    b.HasOne("e_Teretana.Models.Trener", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerKorisnikID");
                });

            modelBuilder.Entity("e_Teretana.Models.Clan", b =>
                {
                    b.HasOne("e_Teretana.Models.Trening", null)
                        .WithMany("PrijavljeniClanovi")
                        .HasForeignKey("TreningID");
                });
#pragma warning restore 612, 618
        }
    }
}
