// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_Teretana.Models;

namespace e_Teretana.Migrations
{
    [DbContext(typeof(TeretanaContext))]
    [Migration("20200522120435_IzmjenaBroj1")]
    partial class IzmjenaBroj1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_Teretana.Models.DbKorisnik", b =>
                {
                    b.Property<int>("DbKorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DbTreningID")
                        .HasColumnType("int");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DbKorisnikID");

                    b.HasIndex("DbTreningID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("e_Teretana.Models.DbNovost", b =>
                {
                    b.Property<int>("DbNovostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemeDodavanja")
                        .HasColumnType("datetime2");

                    b.HasKey("DbNovostID");

                    b.ToTable("Novost");
                });

            modelBuilder.Entity("e_Teretana.Models.DbOprema", b =>
                {
                    b.Property<int>("DbOpremaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KorisnikOpremeDbKorisnikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KrajnjiDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NaCekanju")
                        .HasColumnType("bit");

                    b.Property<string>("NazivOpreme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetniDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sifra")
                        .HasColumnType("int");

                    b.Property<int>("TipZauzetosti")
                        .HasColumnType("int");

                    b.HasKey("DbOpremaID");

                    b.HasIndex("KorisnikOpremeDbKorisnikID");

                    b.ToTable("Oprema");
                });

            modelBuilder.Entity("e_Teretana.Models.DbTrening", b =>
                {
                    b.Property<int>("DbTreningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("TrenerDbKorisnikID")
                        .HasColumnType("int");

                    b.HasKey("DbTreningID");

                    b.HasIndex("TrenerDbKorisnikID");

                    b.ToTable("Trening");
                });

            modelBuilder.Entity("e_Teretana.Models.DbKorisnik", b =>
                {
                    b.HasOne("e_Teretana.Models.DbTrening", null)
                        .WithMany("PrijavljeniClanovi")
                        .HasForeignKey("DbTreningID");
                });

            modelBuilder.Entity("e_Teretana.Models.DbOprema", b =>
                {
                    b.HasOne("e_Teretana.Models.DbKorisnik", "KorisnikOpreme")
                        .WithMany()
                        .HasForeignKey("KorisnikOpremeDbKorisnikID");
                });

            modelBuilder.Entity("e_Teretana.Models.DbTrening", b =>
                {
                    b.HasOne("e_Teretana.Models.DbKorisnik", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerDbKorisnikID");
                });
#pragma warning restore 612, 618
        }
    }
}
